apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "investphere"
---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: investphere-events-service
  namespace: "investphere"
spec:
  replicas: 1
  image: <docker-registry>/investphere-events-service:<tag> 
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "1"
