apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "investphere"
---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: investphere-backtesting-service
  namespace: "investphere"
spec:
  replicas: 1
  image: <docker-registry>/investphere-backtesting-service:<tag>
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
      cpu: 200m
